[build]
  command = "npm build"  # Replace with your build command if applicable
  functions = "netlify/"  # Directory where your Netlify functions are located
  publish = "public"  # Directory where your frontend files are located

[[redirects]]
  from = "/auth/*"  # Match any request starting with /auth/
  to = "/.netlify/functions/auth/:splat"  # Redirect to the auth Netlify function

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"  # Adjust CORS settings as needed
